jobs:
- job: "Clean"
  displayName: "Cleanup"
  workspace:
    clean: all
  steps:
  - checkout: none
  - script: |
      echo "Pipeline.Workspace"
      echo "ls -a '$(Pipeline.Workspace)'"
      ls -a "$(Pipeline.Workspace)"

      echo "Build.ArtifactStagingDirectory"
      echo "ls -a '$(Build.ArtifactStagingDirectory)'"
      ls -a "$(Build.ArtifactStagingDirectory)"

      echo "Build.BinariesDirectory"
      echo "ls -a '$(Build.BinariesDirectory)'"
      ls -a "$(Build.BinariesDirectory)"

      echo "Build.SourcesDirectory"
      echo "ls -a '$(Build.SourcesDirectory)'"
      ls -a "$(Build.SourcesDirectory)"

      echo "Common.TestResultsDirectory"
      echo "ls -a '$(Common.TestResultsDirectory)'"
      ls -a "$(Common.TestResultsDirectory)"
    displayName: "Information"